export default [
    {
        title: "Business Development Executive (Only for Female Candidates)",
        subt: "Easeassist",
        jobt: "📍 Remote",
        jobe: "   💼  0+ years Experience",
        desc: "Immediate Joining !! Fast Growing Business Solutions Startup is looking for passionate Female Business Development Professionals who would l...",
        location: "REMOTE",
        type: "Full-Time",
    },
    {
        title: "Customer Care & Events Executive",
        subt: "Easeassist",
        jobt: "📍 Gurugram",
        jobe: "   💼  1+ years Experience",
        desc: "Looking for a Customer Centric Professional responsible for supporting the design and delivery of the product/Event experience for our custo...",
        location: "INOFFICE",
        type: "Full-Time",
    },
    {
        title: "Enterprise Sales Manager",
        subt: "Easeassist",
        jobt: "📍 Hyderabad/Pune/Bangalore/Kochi",
        jobe: "   💼  2+ years Experience",
        desc: "Resourceful and experienced professional whose primary responsibility is to research and pursue new business leads, work on business proposa...",
        location: "INOFFICE",
        type: "Full-Time",
    },
    {
        title: "Area Sales Manager",
        subt: "V4U HR SOLUTIONS.COM",
        jobt: "📍 Karnataka- Bangalore, Mangalore, Udupi, Hubli, Dharwad, Bellary, Shimoga, Chitradurga, Chikmagalur, Karwar, Haveri, Bidar,Tumkur",
        jobe: "   💼  0+ years Experience",
        desc: "Top ranked company in edu tech industry",
        location: "INOFFICE",
        type: "Full-Time",
    },
    {
        title: "Lead Generation",
        subt: "Easeassist",
        jobt: "📍 Bangalore, Jodhpur, Pune",
        jobe: "   💼  1+ years Experience",
        desc: "Looking for an ambitious and dynamic professional with 1-6 Years of Experience in Inside Lead Generation/Sales/Business Development for Bang...",
        location: "REMOTE",
        type: "Full-Time",
    },
    {
        title: "Project Manager",
        subt: "Easeassist",
        jobt: "📍 Raigarh, Chattisgarh",
        jobe: "   💼  10+ years Experience",
        desc: "A key professional having responsibility of managing a project successfully during its various stages in its life cycle consisting of initia...",
        location: "INOFFICE",
        type: "Full-Time",
    },
]